version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "${PHP_PORT:-9000}:9000"
    networks:
      - restaurant-network

  nginx:
    image: nginx:stable-alpine
    ports:
      - "${NGINX_PORT:-8000}:80"
    volumes:
      - .:/var/www/html
      - ./nginx/grilli.com.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - restaurant-network

networks:
  restaurant-network:
    driver: bridge
