version: "3"
services: 
  server-prod:
    container_name: tv-shows-server-prod
    build: server/.
    ports:
     - "3000:3000"


  client-prod:
    container_name: tv-shows-client-prod
    build:
      context: client/.
    ports:
      - "3100:3000"
    depends_on:
     - server-prod
