version: "3"
services: 
  server-prod:
    container_name: tv-shows-server-prod
    build: server/.
    ports:
     - "${SERVER_PROD_LOCAL_PORT}:${SERVER_PROD_PORT}"


  client-prod:
    container_name: tv-shows-client-prod
    build: client/.
    ports:
      - "${CLIENT_PROD_LOCAL_PORT}:${CLIENT_PROD_PORT}"
    depends_on:
     - server-prod
